#Server settings
server:
  port: 8088

#spring settings
spring:
  datasource:
    url: jdbc:mysql://192.168.18.129:3306/llahn?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: llahn
    password: llahn
    #
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)
#llahn settings
llahn:
  services:
    